### PR TITLE
added cycle.js samples, fixes #3343

### LINKED ISSUE #3343: not included cycle.js samples
There is [cycle.js samples](https://github.com/auth0-community/auth0-cycle-samples) but they not included in [Cycle.js tutorial](https://auth0.com/docs/quickstart/spa/cyclejs). (AUTH-3727)

### PR DESCRIPTION
**Pull request by vmartynets**

### CODE REVIEW

**Comment by chenkie** [comment]
Can you resolve conflicts for this one? Thanks!

**Comment by vmartynets** [comment]
@chenkie done

**Comment by chenkie** [comment]
@Amialc sorry, looks like there's a merge conflict again

**Comment by vmartynets** [comment]
@chenkie done

**Pull request merged**
