### PR TITLE
Updated Lock-iOS documentation

### PR DESCRIPTION
**Pull request by volbap**
- Updated docs according to the requirements specified [here](https://docs.google.com/document/d/1PEKA12k-Gr0q53aXTHNE9SinWV6hkMrFuFLQ7-CX8X8/edit).
- This is not final yet but needs review.
- Remaining work:
  - SMS passwordless login
  - API reference

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
Hello @volbap ! Can you rebase to resolve the conflicts in this PR?

Also, I noticed that the lock screenshots are too large, 750 × 1334. By the rules this may be correct (max width 750) but the image is enormous, you have to actually scroll down. Can you downsize them please so they look nice? Something like 300 × 534 should do the trick.

Thanks!

**Comment by mpaktiti** [comment]
Hello @volbap . Is this PR still valid? It's been open for a while. Are you working on this or should I close it? 

If you address my mobile screenshots comment use [this](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#mobile-screenshots).Thanks.

**Comment by ntotten** [comment]
@chenkie Can you take a look a this and see if we should merge/close?

**Comment by mpaktiti** [comment]
@chenkie Lock iOS docs were updated last week https://github.com/auth0/docs/pull/3466 Not sure if this PR is still relevant.

**Pull request closed without merging**
