### PR TITLE
Remove URL hash fragment from browser's history

### PR DESCRIPTION
**Pull request by alexisluque**
Code side also updated auth0-samples/auth0-javascript-samples#57.

### CODE REVIEW

**Review by joshcanhelp — CHANGES_REQUESTED** [review]
@alexisluque - This change does not affect the browser history, just changes the hash in the address bar, as it did before. I don't know if you can remove it from history once it's there but, if you can, it would probably be with something like `replaceState()`:

https://developer.mozilla.org/en-US/docs/Web/API/History_API

... making sure to do a feature check so you don't call that for browser that don't support it. 

Ping @luisrudge in case he knows of any black magic.

**Comment by luisrudge** [comment]
I agree replaceState is the best to use here. Adoption is pretty good as well: https://caniuse.com/#search=replacestate

**Comment by alexisluque** [comment]
@joshcanhelp I updated with your suggestion.

**Comment by joshcanhelp** [comment]
@alexisluque - Do you have testing steps you can share? And a list of browsers this was tested on?

**Comment by alexisluque** [comment]
@joshcanhelp I've updated the code to fallback on `location.href` if `replaceState` isn't available.
I've tested this in the latest version of Chrome, Firefox, Opera and Edge.
The test steps I used are the following:
* Proceed to login.
* After login is performed, hit the back button, and see that the URL with the access token was removed from the session history.

**Comment by joshcanhelp** [comment]
Thanks @alexisluque! I'll review as soon as I can and get right back to you!

**Review by joshcanhelp — APPROVED** [review]
Just tested in the latest Chrome and it works as expected!

**Comment by joshcanhelp** [comment]
Looks like this page has been replaced 👍

**Pull request closed without merging**
