### PR TITLE
Update to reflect terminology change-Client to Application

### PR DESCRIPTION
**Pull request by rkhoriander**

### CODE REVIEW

**Comment by rkhoriander** [comment]
https://auth0-docs-content-pr-6607.herokuapp.com/docs/api-auth/which-oauth-flow-to-use

Flowchart updated

**Comment by jeffreylees** [comment]
So, this is that weird terminology thing again, but I think that the box that now reads `Application Credentials Grant` needs returned to `Client Credentials Grant` - because that's the name of an Auth0-agnostic protocol (https://tools.ietf.org/html/rfc6749#section-4.4). I think the rest mostly make sense though.

**Review by jeffreylees — CHANGES_REQUESTED** [review]
So, this is that weird terminology thing again, but I think that the box that now reads `Application Credentials Grant` needs returned to `Client Credentials Grant` - because that's the name of an Auth0-agnostic protocol (https://tools.ietf.org/html/rfc6749#section-4.4). I think the rest mostly make sense though.

**Comment by rkhoriander** [comment]
Put in request and waiting on design to fix the wording.

**Comment by rkhoriander** [comment]
Wording fixed.

**Review by jeffreylees — APPROVED** [review]

**Pull request merged**
