### PR TITLE
Update rails dashboard

### PR DESCRIPTION
**Pull request by miketheman**
Hash accessors have changed

### CODE REVIEW

**Comment by aaguiarz** [comment]
@alexisluque please review this, and if it makes sense, let's update it in the samples too

**Comment by miketheman** [comment]
@aaguiarz @alexisluque Any update here?

**Review by alexisluque — APPROVED** [review]

**Comment by miketheman** [comment]
@alexisluque Is this still something useful to the project? I'd like to close out some of these long-open pull requests - it looks like you approved it, and never got around to merging?

**Comment by davidpatrick** [comment]
@miketheman Sorry for monumental delay on this.  I'm grooming through these old PRs and stumbled on this one.  Can you explain why the need for the change in the hash selector? It seems semicolons are still being used in other parts of the tutorials and in the samples.  I am closing for now, but will reopen if needed.

**Pull request closed without merging**
