### PR TITLE
Update interactive.md

### PR DESCRIPTION
**Pull request by franckyj**
Fix small typo

### CODE REVIEW

**Review by frederikprijck — APPROVED** [review]
Thanks!

**Comment by frederikprijck** [comment]
@pdillon @pclavier92 Any chance you can force merge this one? I assume CI is not running due to it being a fork.

**Review by pclavier92 — APPROVED** [review]

**Comment by pclavier92** [comment]
> @pdillon @pclavier92 Any chance you can force merge this one? I assume CI is not running due to it being a fork.

Hi @frederikprijck, the issue here is that we are still on yellow freeze until Wednesday, you should be able to merge this one when the freeze is over. Else can happily do that for you then.

**Comment by frederikprijck** [comment]
Sure, no rush on this at all! Thanks @pclavier92

**Pull request merged**
