### PR TITLE
Fixes for first half of #422

### PR DESCRIPTION
**Pull request by Catografix**

### CODE REVIEW

**Comment by chriskeyser** [comment]
1. In step one, can you finish the sentence with "and perform the below configuration". The screenshot is after it has been configured so it is slightly confusing.
2. there is a hanging comma here after the bracket. It works but correct is to not have the comma. I think this was a carry over i missed.
   `"nameIdentifierProbes": [
   "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
   ],
   }`
3. step 4 - there is no option, should say Write a rule to map...This was a hang over from previous, but it is a quick update, can you make it?

**Comment by Catografix** [comment]
yes ill do these now

**Comment by Catografix** [comment]
What is the 'it' in " Write a Rule to map values to it"?
The step one screenshot is just of the enabling of the SAML2, it doesnt
show any configuration. Would you prefer a different screenshot?

**Comment by chriskeyser** [comment]
Write a rule to make the token issued for the user to an AWS role…

Does that sound good?

**Comment by Catografix** [comment]
I had not begun worked on step 4, (which was step 5 in the issue #422),
theres seems to be alot of changes needed here including an entire step on
creating the role in the IAM console.

Ill work on this now.

**Comment by Catografix** [comment]
Ive worked through the rest of the items in the first section:
https://github.com/auth0/docs/commit/fd0e799f7bd868c0bf56a2b35fe20793c56e9dde

let me know what you think

Il work on the Delegation section next.

**Comment by ntotten** [comment]
@chriskeyser Please confirm if this is ready to be merged.

**Comment by chriskeyser** [comment]
John, really looking great, two minor issues on wrapping (I'm in chrome). See step 5.iii it looks like the image is on the line instead of following. Also see 7, it looks like the trailing line is on the same line as the image. Otherwise ready to go.

**Comment by Catografix** [comment]
Hi Chris

Im glad you're ok with the content.

I fixed the image alignment in step 7 by placing it after the text.
.
In step 5.iii I've tried several things. The code is identical to that in
step 5.i which displays perfectly. Often the live site formats the markup
differently than the preview, so it is best to see it live before trying
too many alternatives.

_In the Delegation section:_
  "The detail here is nice but needs to be updated" - what in this doc is
this referring to?
  "Screens have changed on AWS" and "Role interface in AWS has also
changed" - Ive been taking new screenshots
  "Step 5 says Principal ARN" - where to place this and the exact wording?
  "It'd be nice to then show the code" - Is this the Client-side sample
code alredy present?

**Comment by Catografix** [comment]
In step 5.iii, the text was longer than the image. The solution was to make this its own step.

**Comment by Catografix** [comment]
The image alignment is fixed.

Ive taken a shot at the Delegation section changes. Ive made the additions
requested but I am unclear where to put them.

"A brief description of the AWS add-on..." needs to be written. I will take
a screenshot when I know if the SAML2 addon should remain selected.

**Pull request merged**
