### PR TITLE
Updated to account for removal of user profile locations tab in dashboard

### PR DESCRIPTION
**Pull request by rkhoriander**
https://auth0.slack.com/archives/C1CCJPKAM/p1537227643000100

### CODE REVIEW

**Comment by rkhoriander** [comment]
https://auth0-docs-content-pr-6647.herokuapp.com/docs/user-profile
https://auth0-docs-content-pr-6647.herokuapp.com/docs/user-profile/user-picture

**Comment by khorne3** [comment]
@rkhoriander Do you mind updating user2.png as well to remove the Locations tab?

**Comment by rkhoriander** [comment]
User impersonation is deprecated, so that dropdown isn't showing up in my dashboard any more, which is why I left that image alone. I can perform some image editing to remove the text from the current image?

**Comment by rkhoriander** [comment]
Per discussion at the standup, I removed the outdated screenshots for the deprecated user impersonation feature.

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
