### PR TITLE
Saas images commit has been taken out

### PR DESCRIPTION
**Pull request by camimonse**
Commit with the saas images have been taken out, so we can merge the other commits comming up

### CODE REVIEW

**Comment by camimonse** [comment]
this has to do with #2699 and #2651

**Comment by chenkie** [comment]
@camimonse the sceenshots should be taken on a Mac as per the docs guidelines: https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#screenshots

**Comment by camimonse** [comment]
@chenkie yes, actually this commit should not exist. I was reseting the commit, and I had to name it, i put the new name as "Saas images commit has been taken out", but it seems like it didn´t work. My bad. Anyway, this commit is not blocking us from merging the other commits that we had ( #2699 ), for I redid them in a different branch, so we are ok.

**Comment by chenkie** [comment]
cool thanks 👍

**Pull request closed without merging**
