### PR TITLE
Fix errors and add more information on routes, views for Rails quickstart

### PR DESCRIPTION
**Pull request by joshcanhelp**
Recreated from #6472

### CODE REVIEW

**Comment by albertoperdomo** [comment]
I have noticed that when creating the Auth0 controller, a helper `auth0_helper.rb` is created, which is not used. We ask the user to create another helper `session_helper.rb`.

Would it make sense to move the code from `session_helper.rb` to `auth0_helper.rb` or perhaps add a param to `rails generate` so that the helper is not created?

Thoughts, @joshcanhelp ?

**Comment by albertoperdomo** [comment]
I walked through the quickstart again and it seems much better now.
I'm missing a logout implementation though. I know it was not present in the original user profile Quickstart, so we could address in a separate PR perhaps to get this out of the way.

What do you think?

**Comment by joshcanhelp** [comment]
@albertoperdomo 

> Would it make sense to move the code from session_helper.rb to auth0_helper.rb or perhaps add a param to rails generate so that the helper is not created?

I would recommend the latter since it's possible to exclude helpers from loading based on the app config. I imagine that OmniAuth is auto-including the sessions file so I wouldn't want to change that. Good catch 👍 

> I'm missing a logout implementation ... we could address in a separate PR perhaps to get this out of the way.

Yeah, I think that's the right thing to do here. Let's get these changes out to get it in good shape, then add the logout. Happy to review or help write that when you're ready. 

Thanks!

**Comment by joshcanhelp** [comment]
Fixed up a few syntax indicators and spacing. 

Ready for you @mpaktiti!

**Comment by albertoperdomo** [comment]
>I would recommend the latter since it's possible to exclude helpers from loading based on the app config. I imagine that OmniAuth is auto-including the sessions file so I wouldn't want to change that. Good catch 👍

I have just added the param to skip the helper when generating the controller.

**Comment by joshcanhelp** [comment]
@albertoperdomo - LGTM. Can you approve if this is ready to merge?

**Review by albertoperdomo — APPROVED** [review]

**Comment by albertoperdomo** [comment]
Approved and merged!

**Pull request merged**
