### PR TITLE
quickstart python/flask: Fix missing dependencies and variables

### PR DESCRIPTION
**Pull request by macrat**
Fixed missing dependencies and variables of the quick start of python/flask.

### CODE REVIEW

**Comment by aaguiarz** [comment]
@alexisluque can you check this? Not sure if it's still valid after the latest changes

**Comment by aaguiarz** [comment]
@alexisluque can you check this?

**Comment by alexisluque** [comment]
@aaguiarz it isn't valid for latest changes.

**Comment by aaguiarz** [comment]
We've been updating the Quickstart and these changes no longer apply. Thanks for the PR!

**Pull request closed without merging**
