### PR TITLE
Alemata.angular2 update titles

### PR DESCRIPTION
**Pull request by alemata**

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by alemata** [comment]
@flaviogranero could you review? #1857 should be merged first

**Comment by flaviogranero** [comment]
👍 @chenkie @mpaktiti

**Comment by mpaktiti** [comment]
Merge sequence:
- https://github.com/auth0/docs/pull/1856
- https://github.com/auth0/docs/pull/1857
- https://github.com/auth0/docs/pull/1858

**Pull request merged**
