### PR TITLE
[edit] Resized and tinyPNGed images from CDN

### PR DESCRIPTION
**Pull request by Catografix**
Many of these images were oversized and none had been through tinyPNG

### CODE REVIEW

**Comment by ntotten** [comment]
@Catografix looks like there is a conflict here. I actually did some minification of the images as well, but i didnt resize them.

**Comment by Catografix** [comment]
I think they look better at the smaller widths. I can resubmit these in a new PR if you like.

**Comment by ntotten** [comment]
Please do

**Comment by Catografix** [comment]
OK guess it worked :)

**Comment by Catografix** [comment]
@ntotten this is ready

**Comment by Catografix** [comment]
@ntotten May I remove the Pending label so you will know that this is ready?

**Pull request merged**
