### PR TITLE
Unifying outdated-version alert styles, remove newest-version alerts

### PR DESCRIPTION
**Pull request by jeffreylees**

### CODE REVIEW

**Comment by arielger** [comment]
I added a new container called `version-warning` in the last changes of the `replace-deprecated-ui-comps` branch. We should be using that component for the outdated versioning info.

You can see the changes in the [contributing.md](https://github.com/auth0/docs/blob/replace-deprecated-ui-comps/CONTRIBUTING.md#user-interface) file.

Maybe we can wait to merge the `replace-deprecated-ui-comps` branch and then edit these files and merge this PR.

**Comment by jeffreylees** [comment]
I think that's fine, this one can wait until that one is done. 

OK, so I was switching things to the HTML tag with the `version-alert` class following the example of https://github.com/auth0/docs/pull/4108 - but now we're instead using `version-warning`, is that accurate?

```
::: version-warning
This document covers an outdated version of Lock. We recommend you to <a href="/libraries/lock/v10/migration-guide">upgrade to v10</a>.
:::
```

Can make the changes and merge once your branch is merged with the new items!

**Comment by arielger** [comment]
The `version warning` container is just an abstract wrapper for the html you added in this PR. You can check more info here: https://github.com/auth0/auth0-docs/commit/a6e15cd826d5ca3cbc7624e7fc006e0a9db385ce#diff-448dd27621f6431bd8da9bb73435a56eR135

The idea is to abstract the html of the different containers so if we need to change it someday we can just change it in one place.

**Comment by mpaktiti** [comment]
@jeffreylees The updated UI elements have been merged. So you can update this PR and let me know when it's ready for a review. Thanks!

**Comment by jeffreylees** [comment]
@mpaktiti The changes here are pretty much all already made now except for a couple of the heading changes, so I'll just close this PR.

**Pull request closed without merging**
