### PR TITLE
added UWP seed projects and system requirements

### PR DESCRIPTION
**Pull request by vmartynets**
Must be merged after https://github.com/auth0/Auth0.Windows.UWP/pull/10

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by chenkie** [comment]
@Amialc can you check the conflicts?

**Comment by vmartynets** [comment]
@chenkie fixed

**Comment by mpaktiti** [comment]
Hey @Amialc is this PR still valid? If so can you please resolve the conflicts? Thanks.

**Comment by vmartynets** [comment]
@mpaktiti fixed

**Comment by mpaktiti** [comment]
Hi @Amialc , I [created a new PR](https://github.com/auth0/docs/pull/2631) based on this one but using the latest packager. Thanks! 👍

**Pull request closed without merging**
