### PR TITLE
Improve Passwordless connection doc with sms, email and Auth0.js

### PR DESCRIPTION
**Pull request by hernanhht**

### CODE REVIEW

**Comment by ntotten** [comment]
Looks good to me. NIce job updating the image. We have many oudated ones. :+1:

**Comment by ntotten** [comment]
@hernanhht Would you mind rebasing and sending this again?

**Comment by hernanhht** [comment]
Yes, no problem. I was waiting for the functionality to be available in dashboard and also for the new Lock. When those are ready, I will update this PR.

**Comment by solepano** [comment]
replaced with the new passwordless posts

**Pull request closed without merging**
