### PR TITLE
Seed Project Path Update

### PR DESCRIPTION
**Pull request by mehreencs87**
### Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/auth0/docs#contributing) to this repository.
- [ ] Content conforms to our [Contributing Guidelines](https://github.com/auth0/docs#contributing-guidelines)
- [ ] If applicable, you have added details to the [update feed](https://github.com/auth0/docs/tree/master/updates) 

If you are an Auth0 employee, after you submit this PR create and test a [Review App](https://github.com/auth0/docs#review-apps) to test your changes.
### Description

Please describe your pull request.

Thank you!

PR submitted to the auth0-samples organization needs to be merged too.

### CODE REVIEW

**Comment by iannyanes** [comment]
@mehreencs87 please check the path on this PR. In the new repository
https://github.com/auth0-samples/auth0-php-web-app/tree/master/00-Starter-Seed/basic-webapp

The route indicated in this PR would not reach the seed project.

**Comment by mpaktiti** [comment]
@mehreencs87 The file does not exist any more, please see: https://github.com/auth0/docs/tree/master/articles/server-platforms/php

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
@mehreencs87 @iannyanes 
I will close this PR since this file does not exist any longer. You can create a new PR for [this file](https://github.com/auth0/docs/tree/master/articles/server-platforms/php).

**Pull request closed without merging**
