### PR TITLE
Pravinady patch 2

### PR DESCRIPTION
**Pull request by pravinady**

### CODE REVIEW

**Review by PeterGFernandez — DISMISSED** [review]
Good finds! 8-)

**Comment by rkhoriander** [comment]
@pravinady, Was reviewing PRs and did a quick edit for typos and punctuation. Then realized this might be part of something for which you are requesting reviews from other people/Tami.

**Comment by rkhoriander** [comment]
@PeterGFernandez , since you were specifically requested to review, you have to Approve these changes so that we can move. (Making comments isn't considered a review, unfortunately.)

**Review by PeterGFernandez — APPROVED** [review]
Changes approved

**Pull request merged**
