### PR TITLE
[update] Update to ad-ldap-connector install other platforms

### PR DESCRIPTION
**Pull request by vikasjayaram**
### Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/auth0/docs#contributing) to this repository.
- [x] Commit messages conforms to our [commit message standards](https://github.com/auth0/docs#commit-messages)
- [x] Content conforms to our [Contributing Guidelines](https://github.com/auth0/docs#contributing-guidelines)
- [x] If applicable, you have added details to the [update feed](https://github.com/auth0/docs/tree/master/updates) 
### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by ntotten** [comment]
@sandrinodimattia or @chriskeyser Can you review this?

**Comment by mpaktiti** [comment]
What is the status of this PR?

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by khorne3** [comment]
@mpaktiti Closing this PR, because I already merged in one that fixed the conflicts.

**Pull request closed without merging**
