### PR TITLE
Update Tutorials.md

### PR DESCRIPTION
**Pull request by khorne3**
Remove recursive link.

https://auth0-docs-content-pr-5186.herokuapp.com/docs/tutorials

### CODE REVIEW

**Comment by khorne3** [comment]
@mpaktiti I thought about redirecting to /quickstarts but that goes straight to the home page. So, I left it as is, and removed the recursive link. It looked a bit strange for tutorials to redirect with no mention why. What do you think?

**Comment by mpaktiti** [comment]
@khorne3 Tbh I don't see any point in this page. I think we should remove it altogether. Wdyt?

**Comment by khorne3** [comment]
Sure. I see merits in both sides, but I can go ahead and remove it.

**Comment by mpaktiti** [comment]
@khorne3 Go ahead and remove it, we can always restructure it in the future if we need it. I doubt we have any links towards this page but double check please. Thanks!

**Comment by khorne3** [comment]
We might, but I'll redirect to the Docs home page. I originally thought to redirect to /quickstarts, but that goes to /, so I'll just skip the intermediate step.

**Pull request merged**
