### PR TITLE
[edit] Saas - overall edits, relocated and resized images, description

### PR DESCRIPTION
**Pull request by Catografix**
Replaces #1462

### CODE REVIEW

**Comment by ntotten** [comment]
The images of the login widget are very outdated. Can we update them for lock?

**Comment by Catografix** [comment]
@ntotten For the last image, how do I get **Single sign-on enabled** to show in lock?

**Comment by Catografix** [comment]
Preview OK: https://auth0-docs-content-pr-1539.herokuapp.com/docs/saas-apps

**Comment by ntotten** [comment]
@Catografix I merged, but lets send another with updated screenshots asap.

**Comment by Catografix** [comment]
Oh I was just pushing it

**Pull request merged**
