### PR TITLE
Document how to validate RS access_tokens

### PR DESCRIPTION
**Pull request by rolodato**
### Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/auth0/docs#contributing) to this repository.
- [ ] Content conforms to our [Contributing Guidelines](https://github.com/auth0/docs#contributing-guidelines)
- [ ] If applicable, you have added details to the [update feed](https://github.com/auth0/docs/tree/master/updates) 
### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by ntotten** [comment]
@jerriep @jaredhanson Please confirm

**Comment by jaredhanson** [comment]
Recommend removing the PEM format link.  That is non-standard and doesn't support key rotation.  We should deprecate that endpoint.

**Comment by ntotten** [comment]
@rolodato Will you update per jared's recommendation?

**Comment by rolodato** [comment]
Yes.

**Comment by rolodato** [comment]
@ntotten Fixed.

**Pull request merged**
