### PR TITLE
Fix quotes

### PR DESCRIPTION
**Pull request by kimdhendrick**

### CODE REVIEW

**Comment by albertoperdomo** [comment]
No need to change the quotes. Closing.

**Comment by kimdhendrick** [comment]
Why? This is invalid Ruby code as-is.

**Comment by kimdhendrick** [comment]
@albertoperdomo Maybe I should have provided a description. This change is necessary because the message `Hello from a public endpoint! You don't need to be authenticated to see this.` has a single quote inside the `don't` and thus needs to be wrapped in double quotes `"` instead of single quotes `'`. 
As is, the Ruby code is invalid and breaks when users copy/paste this code.
Please re-open.

**Comment by albertoperdomo** [comment]
Ok. Got it now.
Sorry I failed to see the issue with the single quote. Your explanation helps and you are right.

In fact, I just checked the sample at https://github.com/auth0-samples/auth0-rubyonrails-api-samples/blob/master/01-Authentication-RS256/app/controllers/public_controller.rb and I see an escape character is used, which is way uglier.

**Comment by albertoperdomo** [comment]
In case you'd be interested to do similar fixes, you could submit a similar change in the sample repo (there may be multiple occurrences of this there).

**Review by albertoperdomo — APPROVED** [review]

**Comment by albertoperdomo** [comment]
Thanks for the catch @kimdhendrick and for following up!

**Pull request merged**
