### PR TITLE
WordPress install and config process updates

### PR DESCRIPTION
**Pull request by joshcanhelp**
- Updated the WordPress CMS installation doc to walk through the Setup Wizard screens and remove WordPress-specific plugin installation steps (link to Codex)
- Updated configuration doc to include Auth0 Dashboard screens and new plugin settings
- Made sure we're using capital-P-WordPress everywhere

ping @cocojoe 

https://auth0-docs-content-pr-5621.herokuapp.com/docs/cms/wordpress/how-does-it-work
https://auth0-docs-content-pr-5621.herokuapp.com/docs/cms/wordpress/installation
https://auth0-docs-content-pr-5621.herokuapp.com/docs/cms/wordpress/configuration

### CODE REVIEW

**Review by cocojoe — CHANGES_REQUESTED** [review]
@joshcanhelp in general this looks fine, it probably makes more sense as you have done to point to offical docs for installation methods, although I have to say the offical WP docs are not great for the manual install.

Can you redo your screenshots and remove any personal tenant/client info.  For example with `client-settings-fields` you can just enter some alternative values for the screenshot like

Domain: `yourdomain.auth0.com`
clientId: yourclientid

**Comment by joshcanhelp** [comment]
@cocojoe - The Codex isn't great for that, I agree, but it makes more sense to contribute there to improve it rather than maintain our own steps. 

Updated screens, good call.

**Review by jeffreylees — APPROVED** [review]

**Review by cocojoe — APPROVED** [review]

**Review by mpaktiti — CHANGES_REQUESTED** [review]
@jeffreylees The screenshots do not meet [our guidelines](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#screenshots), can you update them please?

**Comment by joshcanhelp** [comment]
@mpaktiti - I'm actually the one that took those. Can you be more specific about how they don't conform?

**Comment by cocojoe** [comment]
@joshcanhelp Check the screenshots guide above, it does tell you, no plugins showing etc

**Comment by joshcanhelp** [comment]
@mpaktiti - Screenshots updated

@jeffreylees - Made a couple minor changes to the installation page as well

Thank you!

**Pull request merged**
