### PR TITLE
deploy-exts: added db-connections settings section

### PR DESCRIPTION
**Pull request by zxan1285**
Added `Deploy Database Connection Settings` section. We've added this feature in the latest versions for the deploy extensions. Also, added notification about strategies for both Database Connection and Connections sections.

### CODE REVIEW

**Comment by khorne3** [comment]
@zxan1285 Can you please clarify what the following means?

> _This will work only for auth0 connections (strategy === auth0), for non-auth0 connections use `connections`._

Thanks!

**Comment by zxan1285** [comment]
@khorne3 There are different types of connections. `database-connectios` directory is for database connections (https://manage.auth0.com/#/connections/database) settings. And `connections` directory - for social connections (https://manage.auth0.com/#/connections/social).

**Comment by khorne3** [comment]
@zxan1285 I understand the existence of different types of connections, but I'm not sure what we're trying to convey to the reader with

> for non-auth0 connections use connections

If the connection is non-Auth0, they can push settings with a `connections/[connection-name]/settings.json` file, since that seems to be implied? Or are we trying to say to the reader that we can push DB settings only for Auth0 databases, period?

**Comment by zxan1285** [comment]
`Deploy Database Connection Settings` section is all about auth0 connections -  https://github.com/auth0/docs/pull/7214/files#diff-19f7a5e7c43d2817390d87b39fb62c59R89
`Deploy Connections` section is about non-auth0 - https://github.com/auth0/docs/pull/7214/files#diff-19f7a5e7c43d2817390d87b39fb62c59R221

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
