### PR TITLE
Identity Providers - Created table display with icons

### PR DESCRIPTION
**Pull request by Catografix**
I put this together in a few minutes. 

We had the icons just sitting there unused, I thought this would look good.
I've been meaning to fix issue #449. 

If you like it, I should probably have an engineer check my code.

I could also reduce the filesize of some of the icons.

screen shot 2016-06-22 at 12 20 03 am

### CODE REVIEW

**Comment by Catografix** [comment]
Aw it failed :(. I thought I had successfully rebased the branch.

**Comment by Catografix** [comment]
Preview OK second try: https://auth0-docs-content-pr-1584.herokuapp.com/docs/identityproviders

**Comment by ntotten** [comment]
Very nice!!

**Comment by Catografix** [comment]
Thanks! Glad you like :)

**Pull request merged**
