### PR TITLE
Commits for PHP Symfony

### PR DESCRIPTION
**Pull request by camimonse**
At the bottom of the page the instruction was not understandable. For the user was not clear when he has to download the CAs database.

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by camimonse** [comment]
"Instruction on the PHP Symfony improved" fixes #2651

**Comment by camimonse** [comment]
"Snippet will present errors" fixes #2647

**Comment by chenkie** [comment]
@camimonse there's a merge conflict on this one. It also looks like a bunch of unrelated images have been committed with it. Can you remove those and rebase?

**Comment by camimonse** [comment]
Hey @chenkie My branch was always rebased, did you mean reset?
I reverted the changes, you might want to try to merge  now.

**Comment by camimonse** [comment]
@chenkie I am doing the same commits that we have leftover in another branch (NewBranch), where I started resetting the first commit ("update to saas doc images") in #2834 , so we can merge all the commits after it.
For every commit I will link it to the new PR.

**Comment by camimonse** [comment]
for "needed information added" --new PR--> #2836

**Comment by camimonse** [comment]
for "Adding location information" --new PR--> #2838

**Comment by camimonse** [comment]
for "Snippet will present errors" @chenkie you fixed just one part, the new PR is in #2839

**Pull request closed without merging**
