### PR TITLE
error in content-type value.

### PR DESCRIPTION
**Pull request by vit100**
value must be: application/x-www-form-urlencoded

### CODE REVIEW

**Comment by khorne3** [comment]
Confirmed w/ engineering that content-type is indeed json.

**Comment by vit100** [comment]
This is wrong:
According to spec: [https://tools.ietf.org/html/rfc6749#section-4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3)

>  Access Token Request
   The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:

Also if value set to json, then server rejects request with error.
Please review again.

**Comment by khorne3** [comment]
@vit100 Yes, you're correct, my mistake. We will review this and make the appropriate changes. Thank you!

**Comment by vit100** [comment]
Btw sample code defective too. Will create or later




On Fri, Mar 15, 2019 at 1:34 PM -0400, "K Horne" <notifications@github.com> wrote:












@vit100 Yes, you're correct, my mistake. We will review this and make the appropriate changes. Thank you!

**Comment by vit100** [comment]
Pls approve this PR, then I will create new one with reviewed sample, as this one is defective as well - unfortunately internal bug in library `request` make this sample to throw exception

**Review by khorne3 — APPROVED** [review]

**Pull request merged**
