### PR TITLE
Starts a documentation page for the CloudWatch logs extension.

### PR DESCRIPTION
**Pull request by dmark**
Starts a documentation page for the CloudWatch logs extension.

### CODE REVIEW

**Comment by dmark** [comment]
Planning to add the CloudWatch config details this weekend, then I'll update the PR.

**Comment by dmark** [comment]
Haven't gotten to this yet. Away on vacation. Will pick it up when I am back!

**Comment by dmark** [comment]
I believe this can be merged now. I will add some pictures later but the doc is complete as is. Tested the documented process with one of my dev Auth0 tenants and AWS environments.

**Comment by dmark** [comment]
Is there anything more I need to do with this PR? It has been siting idle for a while now. I think it is ready to go but if not, please let me know.

**Comment by rkhoriander** [comment]
Hi, @dmark. We're currently reviewing old PRs and I see this one has been sitting for awhile. For future reference, when it's ready to go, please add a label of "ready-for-review". The concierge on duty that week will then know to review it. Otherwise, if a name in your comment, it can get lost in the queue.

For now, I see that you last commented on Jan 21, and there seem to be some merge conflicts. Do you want to review these? I can merge it for you as soon as you're ready. Thanks!

**Comment by dmark** [comment]
Hi @rkhoriander. I believe this is actually a duplicate of #7222 submitted by @zxan1285. I'll withdraw this one.

**Pull request closed without merging**
