### PR TITLE
Expand New Relic "Monitoring" Information

### PR DESCRIPTION
**Pull request by robcthegeek**
Our team were confused about what to expect after entering the New Relic license key.

Following a support ticket with Auth0, it's come to light that only _fatal_ errors are logged to New Relic - under the application `Auth0 Core`.

### CODE REVIEW

**Comment by khorne3** [comment]
Closing due to inactivity. Would be happy to continue work on this in the future.

**Comment by robcthegeek** [comment]
Not sure why it was marked as `do-not-merge`. [The documentation](https://auth0.com/docs/appliance/dashboard/settings) still doesn't seem to have any information saying that only fatal errors are logged, and under what application. This information is/was useful/needed by our team.

**Comment by khorne3** [comment]
@robcthegeek We've deprecated New Relic and are in the process of updating the docs to remove all references to it. Thanks!

**Comment by robcthegeek** [comment]
Ahhh, that makes sense - thanks for letting me know :)

**Pull request closed without merging**
