### PR TITLE
Platinum subscription level requirement for enterprise SSO

### PR DESCRIPTION
**Pull request by nicosabena**

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
Hello @nicosabena ! There are some problems with the screenshots, would you mind fixing them? 
- The browser cannot show any plugins, customizations, or bookmarks (for example, saas-04.png)
- The browser cannot be in incognito mode (for example, saas-05.png)

**Comment by nicosabena** [comment]
Actually, I meant to change only one single line, but somehow GitHub thinks I changed almost the whole file.

I only wanted to change: 

> Auth0 also supports Enterprise connections (You can request this by opening a [support ticket](https://support.auth0.com))

to this:

> Auth0 also supports Enterprise connections for Platinum level subscriptions (You can request this by opening a [support ticket](https://support.auth0.com))

I'll cancel this PR.

**Comment by mpaktiti** [comment]
@nicosabena Thanks, I updated the file https://github.com/auth0/docs/blob/master/articles/tutorials/using-auth0-with-multi-tenant-apps.md

**Pull request closed without merging**
