### PR TITLE
Add docs for MFA unified API

### PR DESCRIPTION
**Pull request by santiagoaguiar**
Adds documentation for the new MFA api on the Authorization API explorer.

## Depends on #5293

### CODE REVIEW

**Review by kusold — APPROVED** [review]
LGTM.

I do have a non-blocking question though. Are we allowed to use ES6 here? I didn't see anything specifying either way in the CONTRIBUTING.md.

If we are allowed, we may want to consider using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead of `request` because it is likely to become a [web standard](https://fetch.spec.whatwg.org/) and is already shipped in most major web browsers.

**Comment by mpaktiti** [comment]
@erjohnson @santiagoaguiar Is this ready for review or not? Also, should it be merged after https://github.com/auth0/docs/pull/5293 ? Thanks!

**Comment by santiagoaguiar** [comment]
This is ready for review, and should be merged after #5293, yes.

**Comment by santiagoaguiar** [comment]
Sorry for the title, was waiting for Eric's 👍 before changing it, but since he added the ready-for-review I think we are good to go :).

**Comment by khorne3** [comment]
@santiagoaguiar Reverting due to build failure.

**Pull request merged**
