### PR TITLE
Auth0 Token Validation & Authorization as Django Middleware

### PR DESCRIPTION
**Pull request by bholagabbar**
I converted the entire Flask code to Django Middleware which can easily be used to validate and verify all incoming tokens, hence adding support for Django. I had opened https://github.com/auth0/docs/pull/4970 but reissuing it since there was a minor code error. This is tested in production fwiw

To be added here https://auth0.com/docs/quickstart/backend/python/01-authorization

### CODE REVIEW

**Comment by bholagabbar** [comment]
@mpaktiti You guys haven't updated the docs yet. Django is the most widely used framework and there are no docs to tell users how to implement auth in django. You guys really ought to merge this

**Comment by mpaktiti** [comment]
Hi @bholagabbar, looks like this one fell through the cracks, sorry about that. We will review this and get back to you.

cc @aaguiarz

**Comment by bholagabbar** [comment]
I see the docs up on https://auth0.com/docs/quickstart/backend/django

Do we have to write our own code for https://auth0.com/docs/quickstart/backend/django#add-api-authorization or is the section below this a continuation of the same? The header sizes are the same so I cannot distinguish.

Could you please confirm this ?

**Comment by jimmyjames** [comment]
Since there is now a [Django API Quickstart](https://auth0.com/docs/quickstart/backend/django), and the issue backing this PR has been closed, I'm going to close out this PR. Please see the Django Quickstart for that technology, and if you have any issues or questions don't hesitate to reach out (if specific to Django, makes sense to raise issue in that repository). Thanks! 👍

**Pull request closed without merging**
