### PR TITLE
Added "What is an application"

### PR DESCRIPTION
**Pull request by sandrinodimattia**
This covers what we have today: "Applications / APIs". In the future we will need to update this document to be in line with the new and improved naming (API keys, client IDs, stamps, ...)

### CODE REVIEW

**Comment by woloski** [comment]
not convinced about the title

**Comment by woloski** [comment]
seems like this is more "Auth0 Core Concepts"

**Comment by sandrinodimattia** [comment]
Ok makes sense. But this is really focused on the application. How about we create a new section in the left navigation: "Core Concepts". With things like: High level overview (doc which we are planning to write), Applications (this doc), Connections (with links to database, enterprise, social, password less), Rules (link to rules document)?

**Comment by pose** [comment]
@sandrinodimattia @woloski just to prevent duplicated documents: Is this the same as https://github.com/auth0/auth0-cse/blob/master/glossary.md but publicly available?

**Comment by sandrinodimattia** [comment]
@pose, the glossary is a big list with words and their definition. This document only covers "Applications" and is a few pages long. So let's say its covers 1 word of the glossary with a lot of detail ;)

**Comment by pose** [comment]
@sandrinodimattia Awesome, then I'll add a link to the glossary to this. Thanks for the clarification!

**Pull request merged**
