### PR TITLE
Added missing ellipses to ember2js tutorial

### PR DESCRIPTION
**Pull request by fiannolo**
Added missing ellipses to ember2js tutorial according to the github issue: https://github.com/auth0/docs/issues/2671

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by ntotten** [comment]
@chenkie There seems to be some inconsistency on this. I noticed you removed some of the `...` on some samples. Which method do you prefer?

**Comment by chenkie** [comment]
Going to change the approach here to favor fewer ellipses. Will adjust in testing cycle instructions.

**Comment by sheriffderek** [comment]
For the record, there are no ellipsis on the live quickstart as of this date

**Pull request closed without merging**
