### PR TITLE
Update 01-authorization.md

### PR DESCRIPTION
**Pull request by alexisluque**
auth0-samples/auth0-spring-security-api-sample#31

### CODE REVIEW

**Comment by lbalmaceda** [comment]
@alexisluque please correct the indentation to match the rest of the methods.

**Review by lbalmaceda — COMMENTED** [review]
Shouldn't you include a paragraph mentioning **why** you require to set up `cors` or **when** that's needed and **how** that affects the app? If not, it's just a snippet of code you copy and paste and don't know what it's doing.

**Comment by lbalmaceda** [comment]
@alexisluque code was merged yesterday by @aaguiarz. This should be updated and merged as well.

**Review by aaguiarz — APPROVED** [review]
LGTM

**Pull request merged**
