### PR TITLE
Updating Laravel version from 5.5 to 5.7 in urls

### PR DESCRIPTION
**Pull request by james-flynn-ie**
Updated Laravel version to current URLs.

### CODE REVIEW

**Comment by albertoperdomo** [comment]
Thanks for looking into this @james-flynn-ie.

Looking at the [corresponding sample app](https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/01-Login), it seems that it is on Laravel 5.6.12

In [composer.lock](https://github.com/auth0-samples/auth0-laravel-php-web-app/blob/master/01-Login/composer.lock):

```
        {
            "name": "laravel/framework",
            "version": "v5.6.12",
            "source": {
                "type": "git",
                "url": "https://github.com/laravel/framework.git",
                "reference": "82d8165d1ea86bdd81ddfa1db9343fa19e7d1450"
            },
```

Ideally, we'd keep both versions on the tutorial and the sample in sync.
What do you think @joshcanhelp?

* Does it makes sense to set the version in the tutorial to 5.6.12?
* How easy would be to bump the version of the sample to 5.7?

**Comment by joshcanhelp** [comment]
@albertoperdomo - I would set both to be the same, so if we bump the sample to 5.7, I'd bump the QS as well. 

Laravel 5.5 requires PHP 7.0 or higher:

https://laravel.com/docs/5.5/upgrade#upgrade-5.5.0

5.6 (and probably 5.7 as well since it does not mention a PHP req change) requires 7.1.3 or higher:

https://laravel.com/docs/5.6/upgrade#upgrade-5.6.0

The sample is already set at `7.1.3` so moving that to 5.7 would not make a difference. As for what to put on the Quickstart ... moving from 5.5 to 5.7 is a bump in PHP version. Our code should be fine, I don't see anything in there that's deprecated between the two:

https://secure.php.net/manual/en/migration71.deprecated.php

Also, I _just_ ran through the QS in 5.7 and did run run into any problems or differences. 

So ... after typing all that out ... LGTM 😄

**Review by joshcanhelp — CHANGES_REQUESTED** [review]
There is one more instance of `5.5`, search for that here:

https://raw.githubusercontent.com/auth0/docs/7bc958819f3c16a079d9daf16e4afa58c8f61aea/articles/quickstart/webapp/laravel/01-login.md

There are also 2 instances in the header, not entirely sure how those are changed:

screenshot 2018-10-11 12 02 16

**Comment by albertoperdomo** [comment]
Regarding the remaining references:

* The link below "I want to integrate with my app" is automatically added from the titles in the document, so that should be ok.
* The system requirements below that are set in the `index.yml` in the same directory.

Regarding bumping the sample:

* I'd bump the sample to 5.7 too. Would you volunteer do do that @james-flynn-ie?

**Comment by albertoperdomo** [comment]
Added `do-not-merge` label until sample is bumped to make sure they are in sync.

**Comment by james-flynn-ie** [comment]
Thanks for the review, Alberto and Josh.

I've updated the URL on login.md as requested.

The System Requirements were stated in index.yml, and the Laravel version has been updated there.

With regards to the other instance of '5.5' in the header, this seems to be taken from the markdown tags in 01-login.md. Looking at the source for the web page, React seems to fetch the doc's layout using a GET query. The previously updated headers in 01-login.md should populate this automatically.

**Comment by james-flynn-ie** [comment]
Updated sample, https://github.com/auth0-samples/auth0-laravel-php-web-app/pull/30

**Review by joshcanhelp — APPROVED** [review]
LGTM! Thank you!

**Comment by james-flynn-ie** [comment]
Hi, @albertoperdomo , do we need to remove the do-not-merge tag since it has been reviewed by Josh?

**Comment by albertoperdomo** [comment]
Forgot to merge this last week, sorry.
I will do on Wednesday along with https://github.com/auth0-samples/auth0-laravel-php-web-app/pull/30

**Comment by albertoperdomo** [comment]
I want to make sure both app and tutorial are updated more or less at the same time.
In order to do that I have to wait.

**Comment by albertoperdomo** [comment]
Merged! Thanks, @james-flynn-ie!

**Pull request merged**
