### PR TITLE
Part 1 of fixing external images

### PR DESCRIPTION
**Pull request by angelaLazar**

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
Hi @angelaLazar ! Some images are missing the alternate text info. For example 
- this is OK: `Comparing the length of an encoded JWT and an encoded SAML`
- this is not: ``

Could you add some words to describe the images? Thanks!

**Comment by mpaktiti** [comment]
Fixes issue: https://github.com/auth0/docs/issues/1318

**Comment by angelaLazar** [comment]
@mpaktiti Yes I will add the descriptions back for the ones that initially had descriptions but for others it is hard to describe. A lot of the images are data flow diagrams with a lot of pieces.

Also for reference, this fixes about 25% of the the externally hosted images so I will continue to have PRs for this.

**Pull request merged**
