### PR TITLE
needed Information added

### PR DESCRIPTION
**Pull request by camimonse**
In the PHP Symfony tutorial information about that composer is neeeded in order to follow the instructions has been added.

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by camimonse** [comment]
The GitHub issue for "Adding location information" PR is: https://github.com/auth0-samples/auth0-symfony-php-web-app/issues/13

**Comment by camimonse** [comment]
"Needed information added" fixes  #2598

**Comment by chenkie** [comment]
@camimonse there are some conflicts here that are blocking the merge. I also noticed there were some images included in this PR that don't seem to be part of the article. Can you remove those and rebase?

**Comment by camimonse** [comment]
see #2699

**Pull request closed without merging**
