### PR TITLE
Update 01-login.md

### PR DESCRIPTION
**Pull request by mehreencs87**
fixes this https://github.com/auth0/docs/issues/2173

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
Hey @mehreencs87 Should I close this one since you have already created https://github.com/auth0/docs/pull/2229 that addresses the same issue?

**Comment by mehreencs87** [comment]
Hi @mpaktiti same issue but on different tutorials , as you can see here on issue https://github.com/auth0/docs/issues/2173  one pr for UWP JS and one for UWP C#.
Both needs to get merged.

**Comment by mpaktiti** [comment]
Right, sorry! 👍

**Pull request merged**
