### PR TITLE
Adding definition tags for glossary

### PR DESCRIPTION
**Pull request by rkhoriander**

### CODE REVIEW

**Comment by khorne3** [comment]
@rkhoriander One thing: can you fix the merge conflict, please? Other than that, all looks good.

**Comment by rkhoriander** [comment]
Fixed.

**Review by khorne3 — APPROVED** [review]

**Comment by camiblanch** [comment]
I'm seeing some bad changes from this merge in https://github.com/auth0/docs/blob/master/articles/scopes/current/index.md

It seems there was a merge conflict that wasn't resolved properly

**Comment by rkhoriander** [comment]
@camiblanch, thanks! We're pushing out a fix momentarily.

**Pull request merged**
