### PR TITLE
Add Connector article: Create Test Active Directory Domain Controller

### PR DESCRIPTION
**Pull request by twistedstream**
These steps were originally for a customer, but seemed worth adding into docs for others to use.

### CODE REVIEW

**Comment by ntotten** [comment]
Looks great! I'll let @sandrinodimattia accept the PR after he reviews the content

**Comment by sandrinodimattia** [comment]
@twistedstream could you upload the images to the CDN first and change the links?

**Comment by sandrinodimattia** [comment]
@twistedstream could you take the browser screenshots as described in our internal screenshot guideline.
As for the 'Install and configure the AD/LDAP Connector' part you should reference the current documentation for installing the connector to avoid duplicate content.

**Comment by twistedstream** [comment]
@sandrinodimattia fixed the screen shots.

Regarding you comment:

> As for the 'Install and configure the AD/LDAP Connector' part you should reference the current documentation for installing the connector to avoid duplicate content.

So I do point them to the instructions for setting up the new AD/LDAP connection in Auth0 on [this line of the MD code](https://github.com/auth0/docs/pull/154/files#diff-3ceae2d158d890f3e5f4fde6c1441305R78).  But I don't instruct them to follow the remaining instructions on docs (for installing the Connector in Windows) because if they paste the Ticket URL into their browser instead (which is what I instruct them to do), they essentially get the same instructions right?  Plus those should really be opened in a browser on the target machine so they can just click the link to download and install the MSI.

**Comment by twistedstream** [comment]
@sandrinodimattia FYI cleaned up the instructions in that section so they blend a little better with those coming from **Ticket URL**

**Pull request merged**
