### PR TITLE
webtask.io reference removed from hooks docs

### PR DESCRIPTION
**Pull request by zxan1285**
as been requested in https://auth0team.atlassian.net/browse/KEY-908

### CODE REVIEW

**Comment by jeffreylees** [comment]
KEY-908 says

>Remove references to webtask CLI and link to webtask.io from https://auth0.com/docs/hooks#use-the-webtask-editor-to-edit-hooks

I am interpreting this to mean 

1. Remove references to the Webtask CLI in the Hooks doc
2. Link to Webtask.io instead

If it means to remove both, that's confusing as I'm not sure how you edit hooks without using either the editor or the CLI?

No matter how you interpret it, this PR doesn't yet fulfill the intended purpose I don't think?

**Comment by fyockm** [comment]
Sorry, the Jira story was unclear. It has been updated, but pasting here also.

Both of these sections should be removed:
- Use the command-line interface (new customers do not have access to wt-cli, and no one will in the future)
- Use the Webtask Editor to edit Hooks (we want to stop promoting webtask.io)

`wt-cli` functionality will be replaced In the near-ish future. We will have an API to manage hooks. So please do not remove the "Manage Hooks using" list, but just leave "The Dashboard" for now.

**Comment by zxan1285** [comment]
Done

**Comment by zxan1285** [comment]
Done

**Review by jeffreylees — APPROVED** [review]
Nice, LGTM.

**Pull request merged**
