### PR TITLE
[update] indexed top 15 providers based on pageviews

### PR DESCRIPTION
**Pull request by Catografix**
I thought alphabetical listing added no value and buried the most popular providers.

I have indexed the top 15 providers based on domo stats.
The rest sort alphabetically underneath.

Another option would be to sort them to match the manage UI: https://manage.auth0.com/#/connections/social

Do you like this idea?

### CODE REVIEW

**Comment by Catografix** [comment]
Preview OK: https://auth0-docs-content-pr-1613.herokuapp.com/docs/identityproviders

**Comment by Catografix** [comment]
Would you want icons for Enterprise as well?

**Comment by ntotten** [comment]
@Catografix Might be good if you can find them.

**Comment by Catografix** [comment]
I did it already. :)

**Pull request merged**
