### PR TITLE
Extension page updated

### PR DESCRIPTION
**Pull request by vyaspranjal33**
fixing #6819

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@khorne3  when my PR will be reviewed

**Comment by vyaspranjal33** [comment]
@khorne3

**Comment by khorne3** [comment]
Hi @vyaspranjal33. Thanks for your contribution! Unfortunately, the screenshot and text are outdated, so I can't merge this PR -- we can't update one without the other. Please feel free to [add the appropriate screenshot](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#screenshots), otherwise I'll log it to our backlog for later review.

**Comment by vyaspranjal33** [comment]
Ok @khorne3

**Comment by vyaspranjal33** [comment]
@khorne3 appropriate screenshot added

**Comment by vyaspranjal33** [comment]
@erjohnson

**Comment by khorne3** [comment]
@vyaspranjal33 Please review the size/compression requirements. Thank you!

**Comment by vyaspranjal33** [comment]
@khorne3  image has been updated as per  size/compression requirements

**Comment by vyaspranjal33** [comment]
@khorne3  is there still any changes to be made ?

**Comment by khorne3** [comment]
I went ahead and did it myself.

https://github.com/auth0/docs/pull/6875

**Pull request closed without merging**
