### PR TITLE
Updated Xamarin tutorial images, wording & formatting.

### LINKED ISSUE #89: Xamarin tutorial shows outdated images
Image shown on step 3 of Xamarin tutorial (No API) is from an outdated version of the Login Widget. New version has "Lock" logo.

Newer version of login widget (Lock)

### PR DESCRIPTION
**Pull request by TechnikEmpire**
Fixes #89, rewording of content, restructuring of formatting to improve navigation and readability.

### CODE REVIEW

**Comment by auth0build** [comment]
Can one of the admins verify this patch?

**Comment by mpaktiti** [comment]
@TechnikEmpire Please resolve the conflicts so I can review and merge.

**Comment by TechnikEmpire** [comment]
@mpaktiti Don't merge this, just delete it. I had a crash in the middle of resolving this and managed to recover from that, but the file got borked.

**Comment by mpaktiti** [comment]
@TechnikEmpire Thanks for the feedback, I'm closing this PR.

**Pull request closed without merging**
