### PR TITLE
linkedin Photos need to be updated

### PR DESCRIPTION
**Pull request by kaymaylove**
Their portal has changed and so the images in the tutorial no longer match the actual steps necessary

### CODE REVIEW

**Comment by khorne3** [comment]
@kaymaylove Thanks for the screenshots! There were some minor issues I was hoping you could correct -- can you please review the [screenshots guidelines](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#screenshots) and fix? Thank you!

**Comment by kaymaylove** [comment]
I updated these images with the guidelines you provided, please let me know if they suffice. 


linkedin-devportal-1
linkedin-devportal-2
linkedin-devportal-3
linkedin-devportal-4
linkedin-devportal-5
linkedin-devportal-6

**Comment by khorne3** [comment]
@kaymaylove Two final things: can you resize (1500px max) and compress by running through TinyPNG? Thanks

**Comment by kaymaylove** [comment]
Re-uploading, sorry for the mistakes. I appreciate you taking the time to re-review. I set width to 1500px max and ran them through tinypng, please let me know if they hit the criteria :)

linkedin-devportal-1
linkedin-devportal-2
linkedin-devportal-3
linkedin-devportal-4
linkedin-devportal-5
linkedin-devportal-6

**Comment by khorne3** [comment]
@kaymaylove Hey Karen! Sorry for having you jump through all these hoops -- I just reviewed the tutorial, and it looks like a lot of it (not just the screenshots) need to be updated. I'm going to close out this PR and add an action item to our backlog to review all of the content. Thanks for your help!

**Pull request closed without merging**
