### PR TITLE
[edit] Saas - replaced 2 images

### PR DESCRIPTION
**Pull request by Catografix**
### Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/auth0/docs#contributing) to this repository.
- [ ] Content conforms to our [Contributing Guidelines](https://github.com/auth0/docs#contributing-guidelines)
- [ ] If applicable, you have added details to the [update feed](https://github.com/auth0/docs/tree/master/updates) 

If you are an Auth0 employee, after you submit this PR create and test a [Review App](https://github.com/auth0/docs#review-apps) to test your changes.
### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by Catografix** [comment]
I had forgot to push before deploying the heroku last time.
Now its giving an error.

**Comment by Catografix** [comment]
@ntotten Tried heroku 3 times. Nothing loads. Dont know how to view the log. What could be wrong with 2 pngs?

**Comment by Catografix** [comment]
Heroku still gives an application error, but my new Dropbox PR is working, thats why I thought I'd have to rebase.

**Comment by ntotten** [comment]
Yeah, for heroku to work you would have to rebase. I misunderstood what you
are asking.

**Comment by Catografix** [comment]
I did the rebase into the branch, but pushing the branch was rejected. Do I need to fast-forward somehow?
Or if this is only to get heroku too work, and this branch is mergeable, do you still want it tested first?

**Pull request merged**
