### PR TITLE
Updated Postman collection URLs

### PR DESCRIPTION
**Pull request by jeffreylees**
https://trello.com/c/79eAKsYk

https://auth0-docs-content-pr-5180.herokuapp.com/docs/api/info

### CODE REVIEW

**Comment by mpaktiti** [comment]
cc @jerriep

**Comment by jerriep** [comment]
@mpaktiti Yep, those links look good. I assume they are in your personal collection now?

**Comment by jeffreylees** [comment]
Mine. Hopefully, sometime, we can get an org figured out for this, as it'll be the same thing to consider anytime someone leaves, needs to manage them, etc. But it works for now :)

**Comment by jerriep** [comment]
As long as they belong to an Auth0 employee, for now, it is fine :D

**Pull request merged**
