### PR TITLE
Documentation on Grean easyID connections (NOT TESTED)

### PR DESCRIPTION
**Pull request by flensted**
Not sure how to test this, so here are just my suggested additions to the existing documentation.

### CODE REVIEW

**Comment by jerriep** [comment]
@flensted You can test the docs at https://auth0-docs-content-pr-2950.herokuapp.com/docs

**Comment by flensted** [comment]
@jerriep I fixed the broken image links on the overview page. Not sure if it automatically updates the heroku app.

**Comment by jerriep** [comment]
@flensted It is supposed to do it automatically when you push changes to a PR, but in this case it did not do it.

I did it for you manually though, so you can check your changes

**Comment by flensted** [comment]
@jerriep pushed again, but no luck with the automatic heroku deploy it seems

**Comment by jerriep** [comment]
OK @flensted you can check it out again

**Comment by flensted** [comment]
Thx @jerriep. Will proofread and let you know as soon as I'm happy with the content. Guess it's over to your process after that.

**Comment by flensted** [comment]
@jerriep, @ntotten not sure what happened, but it seems the content from this PR is gone from the Heroku app (https://auth0-docs-content-pr-2950.herokuapp.com/docs/identityproviders)

**Comment by mpaktiti** [comment]
Hello @flensted ! The heroku review app works now. Let me know if you have any problems.

**Comment by flensted** [comment]
Guys, I guess the review app doesn't work. But please go ahead and merge this in, once you have done your own review. 
@eugeniop, as agreed - please have a look when you get a chance

**Comment by jerriep** [comment]
Hi @flensted , sorry I was on vacation

I see Eugenio has asked for the people on our side to merge this, so it will probably get merged in the next day or so

**Pull request merged**
