### PR TITLE
Fix `secret` setting in nodejs setup

### PR DESCRIPTION
**Pull request by alexbaumgertner**
Seems like `account.clientSecret` contains base64-encoded secret.

https://github.com/auth0/express-jwt#usage

### CODE REVIEW

**Comment by chenkie** [comment]
Client secrets are actually not Base64 encoded any longer which is why we took out the decoding here :) Only client create prior to Dec 7 will have encoded secrets but anything new won't.

**Comment by alexbaumgertner** [comment]
Thank you for quick answer!

Perhaps I should add a note on new version of secret instead?

**Comment by alexbaumgertner** [comment]
Oh, I found notice – it's already present —

client settings 2016-12-11 21-40-42

**Comment by alexbaumgertner** [comment]
JFI: if you recreate secret it will notice you that your secret not base64 encoded anymore:

client settings 2016-12-18 13-36-43
client settings 2016-12-18 13-37-47

**Pull request closed without merging**
